### ISSUE TITLE
Add XRD as a defined resource

### ISSUE THREAD

**Issue by MisoShiru69** [RadGuild/revup#12]
1. Add XRD as a defined resource.

Enter the arguments for the first function call 
example: PackageName new 200,$tokenEMT 200,$tokenGMT 
No ticks, qoutes or backticks

2. Should the 1st line above read "Enter blueprint name and function-call"?
3. Is the example correct?  When I copy and paste the example and change the token names it still prints the example token names.  
4. quotes is misspelled.  
5. Change the first account created name from "account" to "accout1", same with pubkey.

**Comment by RockHoward** [comment]
1. That should be fixed. This is what this ticket is really about. (Special case first new-account to get it?)
2. No. The message is fine. The example can be improved.
3. User confusion. The required/optional commands issue should clean up the confusion.
4. Yeah. Need to fix that.
5. won't fix. It is possible the user will eventually have control over that though.

**Comment by RockHoward** [comment]
FIxed #1 with a little hard coding.
Fixed #2 and #4 as well.
