### ISSUE TITLE
Make revup installable via crates.io

### ISSUE THREAD

**Issue by RockHoward** [RadGuild/revup#21]
Improve the installation process by making revup available as a crate.

Probably want to wait until after Alexandria for this task as revup may need to go though some adjustments at that time.

**Comment by devmannic** [comment]
Some steps for this while they're on my mind:
* [ ] get a crates.io API token for use with CI and set the Github Action Secret
* [ ] tag the next version to do the publish
* [ ] update the README instructions to simply `cargo install revup`
