### ISSUE TITLE
Package env handling is problematic

### ISSUE THREAD

**Issue by RockHoward** [RadGuild/revup#7]
When running revup if the $package env variable is already set to something besides what the next publish yields, then an error is encountered when trying to run the first call-function after publish . is run.

The workaround is to source .env and then simply run revup again.

Fixing this so that it works 100% of the time may require a rethink of the revup workflow.

**Comment by dRAT3** [comment]
Revup now reads from the .env file directly instead of loading it into std::env::vars and reading from there
